development:
  :username: '6e93d53968881714'
  :password: '0bfa9fcb9853d1f51ee57a'
  :customer_number: '2004381'
  :mode: 'development'

production:
  :username: '6e93d53968881714'
  :password: '0bfa9fcb9853d1f51ee57a'
  :customer_number: '2004381'
  :mode: 'development'
