#development:
#  :username: '3b464bc51a0673f0'
#  :password: '57681971d46ce2fcae46f5'
#  :customer_number: '0009364042'
#  :mode: 'production'
#
#production:
#  :username: '6e93d53968881714'
#  :password: '0bfa9fcb9853d1f51ee57a'
#  :customer_number: '2004381'
#  :mode: 'development'
development:
  :username: '6e93d53968881714'
  :password: '0bfa9fcb9853d1f51ee57a'
  :customer_number: '2004381'
  :mode: 'development'

production:
  :username: '6e93d53968881714'
  :password: '0bfa9fcb9853d1f51ee57a'
  :customer_number: '2004381'
  :mode: 'development'
